server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:3000"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
                maxAge: 3600
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user-service/**
              filters:
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/product-service/**
              filters:
                - RewritePath=/product-service/(?<segment>.*), /$\{segment}

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/payment-service/**
              filters:
                - RewritePath=/payment-service/(?<segment>.*), /$\{segment}

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/order-service/**
              filters:
                - RewritePath=/order-service/(?<segment>.*), /$\{segment}
