server:
  port: 0

eureka:
  client:
    register-with-eureka: true # Eureka서버에 클라이언트로 등록하겠다는 설정
    fetch-registry: true # Eureka 서버로부터 인스턴트들의 주기적으로 가져오겠다는 설정
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: user-service
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# actuator & prometheus 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true

---
server:
  port: 0

client:
  service-url:
    defaultZone: http://discovery-service:8761/eureka
instance:
  prefer-ip-address: true

# load-test 프로파일: 부하테스트용 설정
spring:
  application:
    name: user-service
  config:
    activate:
      on-profile: load-test
  datasource:
    url: ${USER_MYSQL_URL_TEST}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

logging:
  level:
    hana.lovepet.userservice: INFO
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} [LOAD-TEST] [%thread] %-5level %logger{36} - [%X{traceId}] %msg%n"
